### ISSUE TITLE
Rename verb to method

### ISSUE THREAD

**Issue by timofurrer** [LoyaltyNZ/alchemy-framework#6]
Would it be possible to rename the "verb" field to "method"? This would make more sense for a HTTP-like format as HTTP describes it as "method" in: [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4).

I'm interested in this because I'm planning to write a alchemy-framework compatible service.

**Comment by grahamjenson** [comment]
The problem is that HTTP `method` is overloaded when you include the implementing framework. No frameworks (I know of) actually implement methods called GET, DELETE, PATCH... For example `GET /user/` will direct to the application method `list`, but `GET /user/1` will direct to the method `show`.

Renaming it to `method` might be an option but would be in version 2 of the alchemy framework as it would make services incompatible.

**Comment by timofurrer** [comment]
hmm, I think you misunderstood me. I'm talking about the `verb` field inside your message format.
The one here: https://github.com/LoyaltyNZ/alchemy-framework/blame/master/README.md#L123

Are you talking about that, too? If yes, I don't see how it's related. And I totally agree with what you just stated :)
